### ISSUE TITLE
Fix Docs view errors on affected pages

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/cloudfour.com-patterns#1692] opened 2022-03-28 23:20 UTC
If you navigate to the "Docs" view, the Media pattern fails to load. We should resolve this.

https://v-next--cloudfour-patterns.netlify.app/?path=/docs/objects-media--image

<img width="1392" alt="Screen Shot 2022-03-28 at 4 09 48 PM" src="https://user-images.githubusercontent.com/459757/160502998-59458656-9360-45e5-8dea-1609050de748.png">

**Comment by gerardo-rodriguez** [comment] 2022-03-28 23:21
@tylersticka Should this be bumped in priority?

**Comment by gerardo-rodriguez** [comment] 2022-03-29 00:03
The same issue might be happening here? 🤔 

https://v-next--cloudfour-patterns.netlify.app/?path=/docs/objects-embed--image

**Comment by tylersticka** [comment] 2022-03-29 15:58
Looks like an automated update introduced regressions at some point. We should fix it.

**Comment by gerardo-rodriguez** [comment] 2022-03-30 13:05
It might be happening on the Card component as well: https://v-next--cloudfour-patterns.netlify.app/?path=/docs/components-card--content-blocks

**Comment by gerardo-rodriguez** [comment] 2022-04-04 16:15
Also happening on the Deck object: https://v-next--cloudfour-patterns.netlify.app/iframe.html?id=prototypes-speaking-listing--example&viewMode=story&args=#

**Comment by tylersticka** [comment] 2022-04-06 18:15
I changed the name of this since it's impacting more pages and it's been fixed on the Media page already.

**Closed** 2022-04-06 20:51 UTC
Labels: 🐛 bug, size:1, :construction_worker: dev
