### ISSUE TITLE
Circles are not quite circles

### ISSUE THREAD

**Issue by mrgerardorodriguez** [cloudfour/cloudfour.com-patterns#315] opened 2016-07-12 21:50 UTC
Using the iOS simulator, iPad Air, iOS 9.3, the circles are slightly cut off on the right-edge.

![simulator screen shot jul 12 2016 2 48 00 pm](https://cloud.githubusercontent.com/assets/459757/16784896/df7dea84-483f-11e6-86c6-3b06b08f3393.png)

**Comment by tylersticka** [comment] 2016-07-19 18:32
The issue is that iOS Safari at high resolutions doesn't seem to be resizing images and elements _exactly_ the same... they can occasionally be a 1-2 device pixels off.

I just labeled this `won't fix` but then thought of a solution. 😆

**Closed** 2016-07-19 18:56 UTC
Labels: bug
